---
- name: Install apache web server
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Start apache server
  become: yes
  service:
    name: apache2
    state: started
    enabled: yes