---
- name: installing packages for python env
  become: yes
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: creating directory for app
  become: yes
  file:
     path: ./basic-http-server
     state: directory

- name: installing apache2
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes